### ISSUE TITLE
[Tuning] [Question][Enhancement] [Issues] Umbrella issue for multiple observations on MIOpen DB

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1286]
_opened on behalf of @zpwenjh_

**[Category of Issue]**
Issues, Questions, and Enhancement Recommendations

**[Question]**
- [x] **[Issues] sysDB for gfx906**. MI60 DB delivered with release has issues. User observed user DB are generated since kernels “recommended” by system DB will actually be “inapplicable” on the ASIC. Frustrated because user expectations are the kernels recommended by sysDB are tested by MIOpen already.

- [x] **[Enhancement] Find Mode**. Instead of precise matching, can MIOpen implement fuzzy match too? i.e. If exact match is not found in MIOpen DB, the “next promising” candidate might be a “close enough” kernel instead of searching all spaces for the next best one.

- [x] **[Enhancement] Find Mode**. Instead of MIOpen think for the user, can the user have their own search mode, based on a selection or combination of current find modes? 

- [x] **[Question] findDB**. Why is findDB txt file while other DBs are SQL? Is there a plan to turn findDB to SQL too?

**Comment by atamazov** [comment]
> MI60 DB delivered with release has issues. User observed user DB are generated since kernels “recommended” by system DB will actually be “inapplicable” on the ASIC. Frustrated because user expectations are the kernels recommended by sysDB are tested by MIOpen already.

If you see this, then this is just a bug in MIOpen. Please open issue.

> Instead of precise matching, can MIOpen implement fuzzy match too? i.e. If exact match is not found in MIOpen DB, the “next promising” candidate might be a “close enough” kernel instead of searching all spaces for the next best one.

- The first clause says "instead of precise matching", but the second one says "if exact match is not found". Please adjust this.
- Please elaborate the use case.  Do you mean the case when for some problem MIOpen has a record in find-db, but for another "similar" problem there is no record and you would like to borrow the information from the "close enough" record? 
- Are you aware of WTI based Solution selection approach implemented in MIOpen?

> Instead of MIOpen think for the user, can the user have their own search mode, based on a selection or combination of current find modes?

- Find modes cannot be combined. Or maybe you have Search (now often referred as "tuning") modes in mind?
- You are welcome to propose new Find or Tuning modes (as well as whatever else you need).

> Why is findDB txt file while other DBs are SQL? Is there a plan to turn findDB to SQL too?

Due to historical reasons, and because of perf-db and find-db have different performance requirements.

**Comment by zpwenjh** [comment]
> * The first clause says "instead of precise matching", but the second one says "if exact match is not found". Please adjust this.
> * Please elaborate the use case.  Do you mean the case when for some problem MIOpen has a record in find-db, but _for another "similar" problem there is no record_ and you would like to borrow the information from the "close enough" record?
> * Are you aware of WTI based Solution selection approach implemented in MIOpen?

I was intended to add a find mode to avoid exect matching. Using a certain model, directly map a problem to the corresponding fastest algorithm/solver. Now that we have WTI based Solution selection approach, I don't need to spend time thinking about a new model.

**Comment by zpwenjh** [comment]
> > MI60 DB delivered with release has issues. User observed user DB are generated since kernels “recommended” by system DB will actually be “inapplicable” on the ASIC. Frustrated because user expectations are the kernels recommended by sysDB are tested by MIOpen already.
> 
> If you see this, then this is just a bug in MIOpen. Please open defect.

I haven't done this work recently. I'll report the problem next time I observe it.

**Comment by atamazov** [comment]
@zpwenjh Good, thanks!
