### ISSUE TITLE
Updating fdb to have multiple solvers

### ISSUE THREAD

**Issue by cderb** [ROCmSoftwarePlatform/MIOpen#1987]
### Objective: 
We would like to be able to store multiple solvers from the same algorithm in a single find database entry. This is so that if we need to disable a solver, and the next best solver is in the same algorithm grouping, then we would still find it.

### Problem:
Currently our DbRecords will print with 
```cpp
pair.first + ':' + pair.second
```
Which is the key followed by a comma separated list of values.

MIOpen is now keying find db entries by algorithm, 
So printing a find db record looks like this:
```
algorithm:sover,kernel_time,workspace_size,algorithm,network_config
```

In order to store multiple solvers from the same algorithm, find db would need to be re-keyed by the solver name.
The new print would then look like:
```
solver:sover,kernel_time,workspace_size,algorithm,network_config
```

### Solution:
The fdbs need to be updated to the new format. This can be done without much difficulty.

Alternatively we could change the format to:
```
solver:kernel_time,workspace_size,algorithm,network_config
```
Which would be more clean, but would require updating 
a) FindDbData::Visit so that solver_id is not printed
b) the print function DbRecord::WriteIdsAndValues to exclude the first value in pair.second

Another format would be:
```
sover,kernel_time,workspace_size,algorithm,network_config
```
Which would be done easily by removing (pair.first + ':' +) from the output string in DbRecord::WriteIdsAndValues.

**Comment by JehandadKhan** [comment]
@atamazov  As discussed, there is the proposal that @cderb  is working on implementing. Please share your thoughts to help with the PR review process later.

**Comment by atamazov** [comment]
First, a few general remarks. The FDB functionality is part of the lib's core that is engaged in all the Find modes and in Immediate mode. Therefore, changing the structure of FDB might have nontrivial side effects. So first of all, we need to evaluate possible side effects wrt this:
- All places where the FDB is read or written should be reviewed.
  - Special care for MT/MP safety
    - Example of possible problems: #219
- There are some implicit dependencies in our API that must be taken into account
- All tests that count on certain FDB structure must be revised
- Let's also consider possible directions of future development of the lib.

Implementation should be only the second step.

[Recommendation] This is best done by the same people who designed and implemented the existing FDB and other parts of the lib's core, i.e. me, @DrizztDoUrden, @averinevg.

**Comment by atamazov** [comment]
This ticket can be considered as a sub-task of #374, which, among other changes, assumes changing the FDB structure in the same way as proposed here.

[Note] That ticket is dedicated to "old/true" Find 2.0 API topic that we designed over 2 years ago (and whose name "Find 2.0" was overridden by a smaller topic with the API extension in #1503). Please try to not mess with two different Find 2.0 things.

**Comment by cderb** [comment]
@atamazov I agree with your assessment here. #1988 is a mockup of what I understood would need changes to enable this idea, but there is likely something that wasn't accounted for. Maybe it would be a good refresher.

**Comment by atamazov** [comment]
@cderb Some updates for the topmost comment:
- New format of ID:VALUES is: `solver:kernel_time,workspace_size,algorithm`
  - network_config is not necessary in the new format because it is unused since Invokers are implemented for all Solvers.
- Optional requirement: Keep compatibility with old format for reading existing system find-db files.

[Recommendation] Remove all implementation-related details from the topmost comment, e.g. FindDbData::Visit and so on. These are subject to change and can be decided/discussed in the PR.

**Comment by atamazov** [comment]
## TODO
- [x] https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_blocker Review & merge #2033. It is is an initial PR that provides all the necessary functionality plus `WORKAROUND_ISSUE_1987` for backward compatibility.
- [ ] https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_normal Regenerate all find-dbs in the [new format](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1987#issuecomment-1475425835) and remove `WORKAROUND_ISSUE_1987`.
  - [x] #2151 
  - [ ] remove `WORKAROUND_ISSUE_1987`

**Comment by cderb** [comment]
Addressed in #2033 
FDB files to be updated with solvers.

**Comment by cderb** [comment]
#2151 merged which updates the MI100 and MI200 fdbs to this new format.

**Comment by atamazov** [comment]
@cderb Please reopen this because WORKAROUND_ISSUE_1987 is not removed, see https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1987#issuecomment-1476798413

**Comment by atamazov** [comment]
@cderb ...or find-dbs for Vega and Navi are still in old format?

**Comment by atamazov** [comment]
@cderb Oops, it seems like the title of #2151 is misleading. Actually all system find-dbs updated, and now we can remove WORKAROUND_ISSUE_1987.

**Comment by atamazov** [comment]
> @cderb Please reopen this because WORKAROUND_ISSUE_1987 is not removed, see [#1987 (comment)](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1987#issuecomment-1476798413)

@cderb Ping

**Comment by atamazov** [comment]
@cderb @junliume @JehandadKhan The following system find-db files are still in the old format:
- gfx803_36/64.HIP.fdb.txt
- gfx900_56/64.HIP.fdb.txt
- gfx906_60/64.HIP.fdb.txt
- gfx1030_36.HIP.fdb.txt
- gfx803_36/64.OpenCL.fdb.txt
- gfx900_56/64.OpenCL.fdb.txt
- gfx906_60/64.OpenCL.fdb.txt
- gfx90878.OpenCL.fdb.txt

These prevent us from getting rid of `WORKAROUND_ISSUE_1987`, which is actually nice to remove in order to optimize and clean up the code.

Proposal:
- OpenCL databases: remove as we do not support OpenCL anymore (@atamazov)
- gfx803 and gfx900/MI25 databases: remove (@atamazov) or re-export (@cderb). I would vote for removal, but there is something to discuss:
  - Recent ROCm does not support gfx803 and gfx900. However MIOpen is able to support ROCm down to 3.7 (unoffifically), which means that at least somehow the users can install some older ROCm and use recent MIOpen with MI25. So this is questionable.
- gfx906_60/64.HIP.fdb.txt and gfx1030_36.HIP.fdb.txt: re-export from Tuna (@cderb)

What do you think?

@junliume Please re-open this ticket because https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1987#issuecomment-1476798413 is incomplete.

**Comment by JonathanLichtnerAMD** [comment]
Closing since MIOpen is being migrated to [ROCm/rocm-libraries](https://github.com/ROCm/rocm-libraries).  Please re-open there if you believe this is still an issue.
