### ISSUE TITLE
[tests] Follow-up of WORKAROUND_SWDEV_306318

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1992]
### History

- #1619
  - W/A totally disables the solver
- #1639 
  - Extends the W/A: it totally disables all the Solver's tests
- #1675 
  - Narrows down the W/A introduced in `#1619`. The solver is now applicable for configs where `!(1x1 && C%8 != 0)`

### TODO
- [x] Resolve https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1675/files#r1111293365
  - Fixed in #2011
- [x] Resolve https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1639/files#r1111294406
  - Fixed in #2011
- [x] @qianfengz to review all the PRs mentioned above, see https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1619#issuecomment-1191024384
- [x] Narrow down the W/A in tests introduced in #1639.
  - [Informative] The tests must cover all cases where `!(1x1 && C%8 != 0)`
  - Fixed in #2011

[Attribution] @junliume @johnny-keker https://github.com/ROCmSoftwarePlatform/MIOpen/labels/testing https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_blocker

**Comment by qianfengz** [comment]
@junliume So for the issues left by PR 1675 and PR 1639, we will need to make a P.R to get them done, I will do this next week

**Comment by atamazov** [comment]
@qianfengz 
> @junliume So for the issues left by PR 1675 and PR 1639, we will need to make a P.R to get them done, I will do this next week

Yes, this is to check the first two checkboxes in the topmost comment.

The 3rd checkbox is done AFAIU, please check it.

Please also take care about the 4th checkbox. This is another leftover of #1675 (that should narrow W/A in tests, but missed that).
