### ISSUE TITLE
PR Testing Updates

### ISSUE THREAD

**Issue by daniellowell** [ROCmSoftwarePlatform/MIOpen#586]
### Faster verification time
- [x] a. Create GPU convolution reference kernel (@carlushuang)
&nbsp;&nbsp;&nbsp;&nbsp;i. Carlus’ implementation: [link to naive_conv](https://github.com/carlushuang/mkldnn_test/blob/master/conv/naive_conv.h)
&nbsp;&nbsp;&nbsp;&nbsp;ii. PR: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/583
- [x] b. Create test for GPU reference kernel against CPU reference (@carlushuang) => PR: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/583
- [x] ~~c. Verification GPU kernel to compare buffers and another computes RMS (@fronteer)~~
~~_(Note: For multi-solver testing reuse reference buffer)_~~
rejected due to concern of excessive GPU memory consumption [583_comment](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/583#discussion_r523121195)
### Get rid of CI garbage 
- [ ] a. Get rid of test redundancy -- issue #816
- [x] b. Get rid of hcc (@daniellowell)
- [x] c. Spilt nodes between MIGraphX and MIOpen (@daniellowell)
- [ ] d. Look at input configs to see if they test relevant code (everyone) -- #817

### More comprehensive PR testing
- [ ] a. Realistic testing -- #818
- [ ] b. Test all solvers (@atamazov, @DrizztDoUrden) -- #819
  - 1. Initially test offline as a weekly test
  - 2. Need a C++ API to cycle through all applicable solvers for each config
  - 3. Invokers should have a callback that has access to the output buffer
- [ ] c. ctests for specific solvers; e.g., test_igemm2d (@asroy) -- #820

### iGEMM component testing
- [ ] a. isApplicable (@ltqin) -- #821
- [ ] b. perf param selection (@shaojiewang) -- #822
  - requires parallel compilation
- [ ] c. transformation test --  address calculation (@zjing14) -- #823
- [ ] d. GEMM testing – make the test case tunable to test more GEMM sizes; e.g., 64x64 and 128x128 tests (@jane-zxy) -- #824

### Convolution stability tests
- [ ] a. isApplicable testing -- #825
- [ ] b. Numerical stability testing (NaN and Inf) (@asleepzzz) -- #826
  - Input / Initialization patterns NaN / Inf / 0’s / 1’s
- [ ] c. Long running segmentation fault scan -- #827
- [ ] d. Database verification -- check for errors (@JehandadKhan) -- #828

### Jenkins improvements
- [ ] a. Implement priority levels in the Jenkins queue -- #829
- [ ] b. Testing hints, to reduce scale of testing, enhance testing -- #830

**Comment by atamazov** [comment]
All sub-tasks moved to separate tickets. And we now have [respective github Project](https://github.com/ROCmSoftwarePlatform/MIOpen/projects/9#card-57780622) for tracking.
